### ISSUE TITLE
[IMPLEMENTATION] NetworkX algorithm in a parallel fashion

### ISSUE THREAD

**Issue by leogm99** [joaquinhojman/TPF#2]
The main goal is to assess how difficult it is to adapt the existing library to support parallelization in some of the algorithms. 

I would not mess around with anything more complicated than [multiprocessing](https://docs.python.org/3/library/multiprocessing.html) or [joblib](https://joblib.readthedocs.io/en/stable/) for the moment, nor try to encapsulate or hide the parallelization method.

Edit:

- Track time taken

**Comment by joaquinhojman** [comment]
Using **joblib** it was possible to implement in a parallel way the algorithm **all_pairs_shortest_path_length**: [commit here](https://github.com/joaquinhojman/networkx/commit/80bdb2a55b632f990523e27bf4f3b9e196786c3e).

[All-pairs shortest path length algorithm](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.unweighted.all_pairs_shortest_path_length.html#networkx.algorithms.shortest_paths.unweighted.all_pairs_shortest_path_length)

Now the algorithm receives a parameter (false by default) that allows to execute the algorithm in its classic form or in its parallel form.

All networkx tests continued to succeed when run with the modified algorithm in its parallel version.

When using multiprocessing to parallelize, one of the tests (not directly related to shortest_path algorithms) failed with a serialization exception. Maybe related to https://github.com/networkx/networkx/pull/2265#issuecomment-249754905.

time taken (including cloning the networkx repository, mounting the virtual environment and trying without success install watson): 2 hours, 30 minutes.

**Comment by joaquinhojman** [comment]
Using Joblib was also possible to implement in a parallel way the algorithm betwennes_centrality: [Commit](https://github.com/joaquinhojman/networkx/commit/d6fa2f206d7a725db364c8431da79e4c6044991c)

[Betweness Centrality](enerated/networkx.algorithms.centrality.betweenness_centrality.html)

All networkx tests continued to succeed when run with the modified algorithm in its parallel version.

Time taken: 2 hours, 30 minutes
